pipeline:
  identifier: Build_fuzirako_kubernate_1704209165655
  name: Build kubernate
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: fuzirako/kubernate
  stages:
    - stage:
        name: build kubernetes
        identifier: build_kubernetes
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: ls -la
        tags:
          kubernetes: ""
        delegateSelectors:
          - docker-delegate
        when:
          pipelineStatus: All
